<a href="https://colab.research.google.com/github/Mabinogit/AI-Image-Classification/blob/main/Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as


SyntaxError: invalid syntax (<ipython-input-1-bed1df6fed86>, line 1)

In [2]:
numpy as np

SyntaxError: invalid syntax (<ipython-input-2-78d725482125>, line 1)

In [3]:
import numpy as np

Numpy Array

In [4]:
np_arra = np.array([1,2,3,4,5])

In [5]:
print(np_arra)


[1 2 3 4 5]


In [6]:
type(np_arra)

numpy.ndarray

In [7]:
# creating 1D array

In [8]:
a = np.array([1,2,3,4,5])

In [9]:
print(a)

[1 2 3 4 5]


In [10]:
a.shape

(5,)

In [11]:
# creat 2D array#

In [12]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
b.shape

(2, 5)

In [18]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)

In [19]:
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [20]:
# intial place holders in numpy arrays

In [21]:
# creat numpy array of zeros

In [22]:
x = np.zeros((4,5))

In [23]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
#creat numpy array of 1

In [25]:
y = np.ones((3,3))

In [26]:
#creat array of particular value

In [28]:
z = np.full((5,4),5)

In [29]:
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [30]:
# creat an identity matrix

In [31]:
a = np.eye(5)

In [32]:
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
# creat numpy array with random values

In [34]:
u = np.random.random((3,4))

In [35]:
print(u)

[[0.343247   0.09859072 0.58647905 0.8080025 ]
 [0.9005387  0.73381083 0.18148821 0.81095391]
 [0.02612266 0.41796951 0.9018239  0.03921845]]


In [36]:
# creat numpy array with random values within a specific range

In [37]:
f = np.random.randint(1,100,(5,5))

In [38]:
print(f)

[[22 31 30 59 30]
 [56  3 22 86 24]
 [60 76 32 79 40]
 [66 33 42 81 27]
 [21 63 62 32 78]]


In [39]:
#creat array of evenly spaced values -- specifying number of values

In [40]:
s = np.linspace(1,30,5)

In [41]:
print(s)

[ 1.    8.25 15.5  22.75 30.  ]


In [42]:
#creat array of evenly spaced values --> specifying the step

In [46]:
g = np.arange(1,30,5)


In [47]:
print(g)

[ 1  6 11 16 21 26]


In [48]:
# converting list into numpy array

In [49]:
list2 = [1,2,5,7,4,5,7,8,9,2,46,]

np_array = np.asarray(list2)
print(np_array)

[ 1  2  5  7  4  5  7  8  9  2 46]
